src/HyperionStudios/GxpBundle/Entity/BannerImage.php
<?php
// src/HyperionStudios/GxpBundle/Entity/Image.php
namespace HyperionStudios\GxpBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity
 * @ORM\Table(name="pgxp_banners")
 * @ORM\HasLifecycleCallbacks()
 */
class BannerImage
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $path;
    
    /**
     * @Assert\Image(
     *     maxSize = "250k", 
     *     minWidth = 468,
     *     maxWidth = 468,
     *     minHeight = 60,
     *     maxHeight = 60
     * )
     * @ Assert\NotNull(groups={"registration"})
     */
    protected $file;
    
    
    private $temp;
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return BannerImage
     */
    public function setPath($path)
    {
        $this->path = $path;
    
        return $this;
    }

    /**
     * Get path
     *
     * @return string 
     */
    public function getPath()
    {
        return $this->path;
    }
    
    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null) {
        $this->football = $file;
        $this->file = $file;
        // check if we have an old image path
        if (isset($this->path)) {
            // store the old name to delete after the update
            $this->temp = $this->path;
            $this->path = null;
        } else {
            $this->path = 'initial';
        }
    }
        
    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile() {
        return $this->file;
    }

    public function getAbsolutePath() {
        return null === $this->path
            ? null
            : $this->getUploadRootDir().'/'.$this->path;
    }

    public function getWebPath() {
        return null === $this->path
            ? null
            : $this->getUploadDir().'/'.$this->path;
    }

    protected function getUploadRootDir() {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    protected function getUploadDir() {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads/banners';
    }
    
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload() {
        if (null !== $this->getFile()) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->path = $filename.'.'.$this->getFile()->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {
        if (null === $this->getFile()) {
            return;
        }

        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->getFile()->move($this->getUploadRootDir(), $this->path);

        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            unlink($this->getUploadRootDir().'/'.$this->temp);
            // clear the temp image path
            $this->temp = null;
        }
        $this->file = null;
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        $this->temp = $this->getAbsolutePath();
    }
    
    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if ($this->temp) {
            unlink($this->temp);
        }
    }

}

src/HyperionStudios/GxpBundle/Resources/views/Snippets/nobanner.html.twig
{# src/HyperionStudios/GxpBundle/Resources/views/Snipperts/nobanner.html.twig #}

 <a class="banner-link" href="{{ path('ProjectGxp_server', {'id': server.id}) }}">
    {% if server.bannerImage.webPath %}
        <img src="{{ asset(server.bannerImage.webPath) }}" class="bannerImg img-responsive" alt="{{ server.name }}">
    {% else %}
        <div class="no-banner"><p>No Banner</p></div>
    {% endif %}

    {% if server.creationDate|date("U") > "-7 days"|date("U") %}
        <span class="label label-success new-label">New</span>
    {% endif %}
</a>

src/HyperionStudios/GxpBundle/Resources/views/Snippets/serverListing.html.twig
{# src/HyperionStudios/GxpBundle/Resources/views/Snipperts/serverListing.html.twig #}

<div class="row">
    <div class="col-md-2 col-sm-2 col-xs-2">
        <div class="f32"><span class="flag {{ server.country|lower }}" title="{{ server.country|country }}"></span></div>
        <h4>{{server.name}}</h4>
        <div>
            {% if server.version %}
            Version: {{ server.version }}
            {% endif %}
        </div>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-6">

       {% include 'ProjectGxpBundle:Snippets:nobanner.html.twig' %}

        <div class="row">
            <div class="col-md-12">
                {# display server ip #}

                <div class="input-group input-group-sm ip-copy-group">
                    <span class="input-group-btn">
                        <a  class="btn btn-default ip-copy-btn">
                            Copy
                            <span class="checkmark glyphicon glyphicon-ok-sign" style="display:none;"></span>
                        </a>
                    </span>
                    <input value="{{ server.ip }}:{{ server.port }}" type="text" readonly="readonly" class="form-control ip-copy-text" >
                </div>

            </div>   
        </div>
    </div>
    <div class="col-md-2 col-sm-2 col-xs-1">
        <h4>
        {% if server.playersCount and server.maxPlayersCount %}
            {{ server.playersCount }}/{{ server.maxPlayersCount }}
        {% elseif server.maxPlayersCount %}
            0/{{ server.maxPlayersCount }}  
        {% elseif server.playersCount %}
            {{ server.playersCount }}
        {% else %}
            N/A
        {% endif %}
        </h4>
    </div>
    <div class="col-md-2 col-sm-2 col-xs-3">
        {#{ server.isOnline }#}
        <div class="server-status">
            {% if server.isOnline %}
                <h4 class="label label-success">Online</h4>
            {% else %}
                <h4 class="label label-danger">Offline</h4>
            {% endif %}
        </div>
        <div class="server-stats">
            {% set upPercent = server.UptimePercentage() *100 %}
            {% spaceless %}
            <div 
            {% if upPercent <= 30 %}
                class="text-danger"
            {% elseif upPercent <= 70 %}
                class="text-warning"
            {% else %}
                class="text-success"
            {% endif %}
            >Uptime: {{ (upPercent)|number_format(2,'.',',') }}%</div>
            {% endspaceless %}
            <div>Votes: {{ server.totalVotes }}</div>
        </div>
    </div>
</div>
<div class="row server-tags">
     {% for tag in server.tags %}
        <a href="{{ path('ProjectGxp_servers', {'type': server.type.name, 'tags': tag}) }}" class="btn btn-sm btn-primary">{{ tag }}</a>
     {% endfor %}
</div>       